CREATE Table Injury (
InjuryID INT AUTO_INCREMENT NOT NULL,
InjuryType VARCHAR(50) NULL,
InjuryLocation VARCHAR(50) NULL,
InjuryDuration INT NULL,
PRIMARY KEY (InjuryID)
);

CREATE Table League (
LeagueID INT AUTO_INCREMENT NOT NULL,
LeagueProStatus BIT NOT NULL,
LeagueStartDate DATE NOT NULL,
LeagueEndDate DATE NOT NULL,
PRIMARY KEY (LeagueID)
);

CREATE Table Sport (
SportID INT AUTO_INCREMENT NOT NULL,
SportType ENUM('Professional', 'Amateur') NOT NULL,
SportName ENUM('Baseball', 'Football', 'Soccer', 'Hockey', 'Basketball') NOT NULL,
LeagueID INT NOT NULL,
PRIMARY KEY (SportID),
FOREIGN KEY (LeagueID) REFERENCES League(LeagueID)
);

CREATE Table Team(
TeamID INT AUTO_INCREMENT NOT NULL,
TeamName VARCHAR(50) NOT NULL,
TeamLocation VARCHAR(50) NOT NULL,
TeamMascot VARCHAR(50) NOT NULL,
LeagueID INT NOT NULL,
PRIMARY KEY (TeamID),
FOREIGN KEY (LeagueID) REFERENCES League(LeagueID)
);

CREATE Table Player(
PlayerID INT AUTO_INCREMENT NOT NULL,
PlayerFName VARCHAR(50) NOT NULL,
PlayerLName VARCHAR(50) NOT NULL,
PlayerInjured BIT NOT NULL,
PlayerPay INT NOT NULL,
SportID INT NOT NULL,
TeamID INT NOT NULL,
PRIMARY KEY (PlayerID),
FOREIGN KEY (SportID) REFERENCES Sport(SportID)
);

CREATE Table InjuryStatus (
InjuryStatusID INT AUTO_INCREMENT NOT NULL,
PlayerID INT NOT NULL,
InjuryID INT NOT NULL,
PRIMARY KEY (InjuryStatusID),
FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID),
FOREIGN KEY (InjuryID) REFERENCES Injury(InjuryID)
);